---
title: "Examples --- Reviced Simplex Algorithm"
---

```{r message = FALSE, warning = FALSE, include = FALSE}

library(simplexR)

```

```{r, message = FALSE, warning = FALSE, include = FALSE, echo = FALSE}

source("_gMOIP_functions.R")

```


In simplex method the entire simplex tableau is updated while a small part of it is used. The revised simplex method uses exactly the same steps as those in simplex method. The only difference occurs in the details of computing the entering variables and departing variable

## Tableau Form

```{r}

A_ <- matrix(c(
  2, 1,
  1, 2,
  4, 1
), nrow = 3, ncol = 2, byrow = TRUE, dimnames = list(c("R1", "R2", "R3"), c("x1", "x2")))

b_ <- c(22, 23, 40)
c_ <- c(3, 2)

primal_feasible_tableau <- construct_tableau(A_, b_, c_)
primal_feasible_tableau

```

## Reviced Simplex Algorithm

```{r}

## optimal tableau:
##    x1 x2          s          s s  b
## R1  0  1 -0.3333333  0.6666667 0  8
## R2  0  0 -2.3333333  0.6666667 1  4
## R3  1  0  0.6666667 -0.3333333 0  7
## z   0  0  1.3333333  0.3333333 0 37

A <- cbind(A_, diag(nrow(A_)))
b <- b_
obj <- c(c_, rep(0, 3))
basic <- c(3, 4, 5)

reviced_primal_simplex(A, b, obj, basic)

```

